name: FromAPI
api_key_name: AZURE_API_KEY2
model: gpt-4.1
config:
  client:
    _target_: openai.AzureOpenAI
    # azure_endpoint: https://petunia-gpt4o-mini.openai.azure.com/
    azure_endpoint: https://nicolasflow.openai.azure.com/
    api_key: ${env_variable:'${llm.api_key_name}'}
    api_version: 2024-02-15-preview
  model: ${llm.model}
  config_inference:
    max_tokens: 4096
    temperature: 0.5
    top_p: 1.0
  max_retries: 20



