# WARNING : Claude is not compatible with the FromAPI class right now, API call is client.messages.create and there is no seed
name: FromAPI
api_key_name: ANTHROPIC_API_KEY
model: claude-3-sonnet
config:
  client:
    _target_: anthropic.Anthropic
    api_key: ${env_variable:'${llm.api_key_name}'}
  model: ${llm.model}
  kwargs:
    top_p: 0.9




