name: FromAPI
api_key_name: MISTRAL_API_KEY
model: mistral-large-cc
config:
  client:
    _target_: openai.OpenAI
    api_key: ${env_variable:'${llm.api_key_name}'}
    base_url: https://api.mistral.ai/v1
  model: ${llm.model}
  kwargs:
    top_p: 0.9
