name: FromAPI
api_key_name: OPENAI_API_KEY
model: gpt-4o-mini
config:
  client:
    _target_: openai.OpenAI
    api_key: ${env_variable:'${llm.api_key_name}'}
  model: ${llm.model}
  config_inference:
    max_tokens: 4096
    temperature: 0.5
    top_p: 0.9
  max_retries: 20




