name: VLLM
model: /lustre/fsn1/projects/rech/imi/upb99ot/hf/Qwen3-4B # vllm serve Qwen/Qwen2.5-1.5B-Instruct
config:
  dtype_half: True  # True on v100
  config_server:
    do_server: True
  model: ${llm.model}
  config_inference:
    top_p: 0.9




