# Hyperparameters
n_steps_max : 100

# Secondary settings
do_curriculum: True

# Logging
log_dir : logs
do_wandb : False
wandb_config:
  project : wandb_project_example
  entity : wandb_entity_example
do_cli : True
do_tb : True
do_csv: True
do_tqdm : True
do_profiling: True
config_logs:
    # The directory to save logs to.
    log_dir: ${log_dir}
    # Whether to log the run on log_dir/<run name>
    do_log_on_new: True
    # Whether to log the run on log_dir/_last
    do_log_on_last: True


# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - env : minigrid
  - agent : cg
  - llm : dummy
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .