# Hyperparameters
n_steps_max : 100

# Secondary settings
do_curriculum: False

# Logging
log_dir : logs
do_wandb : False
wandb_config:
  project : wandb_project_example
  entity : wandb_entity_example
do_tb : True
do_cli : True
do_tqdm : True
config_logs:
    # The directory to save logs to.
    log_dir: ${log_dir}
    # Whether to log the run on log_dir/<run name>
    do_log_on_new: False
    # Whether to log the run on log_dir/_last
    do_log_on_last: True


# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - env : minigrid
  - agent : hcg2
  - llm : openai
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .