# Hyperparameters
n_episodes : 100
n_training_episodes: 10
n_eval_episodes: 0

# Logging
# log_dir : /scratch/rech/genluq01/upb99ot/logs_llm4code
log_dir : logs
do_wandb : False
wandb_config:
  project : wandb_project_example
  entity : wandb_entity_example
do_tb : True
do_cli : True
do_tqdm : True



# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - env : minigrid
  - agent : hcg
  - llm : openai
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .