name: Minigrid
config:
  # Global
  do_curriculum: ${do_curriculum}
  # Environment
  viewsize: 7
  # Representation
  sections_docstring:
    - Description
    - Mission Space
    # - Action Space
    - Observation Encoding
    - Rewards
    - Termination
  # Rendering
  render_mode_train: rgb_array
  render_mode_eval: human
  n_videos_logged: 4

  # Logging
  config_logs: ${config_logs}