name: Minigrid
config:
  # Global
  do_curriculum: ${do_curriculum}
  # Environment
  viewsize: 7
  # Representation
  list_sections_docstring:
    - Description
    - Mission Space
    # - Action Space
    - Observation Encoding
    - Rewards
    - Termination
  # Feedback
  list_feedback_keys:  # dict_agg_fb["position"] = {mean_0: 4}
    - custom  # custom feedback from the tasks
    - position  # initial position and final position
    - duration  # duration and maximal duration
    - distance_start_to_end
    - map # dict_agg_fb["map"] = [bla, bla, bla]
  # Rendering
  render_mode_train: rgb_array
  render_mode_eval: human
  n_videos_logged: 4

  # Logging
  config_logs: ${config_logs}