name: CG
config:

  # Which prompt to use
  list_prompt_keys:
    - system
    - env
    - code_env
    - code_task
    - controller_structure
    - example_answer
    - task
    - task_description
    - task_map
    - instructions

  # The number of tasks to do. If none, will do all tasks.
  n_tasks_to_do: null

  # The number of completions to make per inference on a task
  n_completions: 1

  # The number of episodes on which a controller will be evaluated on a task
  n_episodes_eval: 1

  # The parameter for the pass@k metric
  k_pass: ${eval:'min(${agent.config.n_completions}, 10)'}

  # The LLM config to use
  llm: ${llm}

  # The config for parallel running
  config_parallel:
    # method: thread_pool # either thread_pool or sequential
    method: sequential
    max_workers: 3

  config_debug:
    # Whether to breakpoint on inference events
    breakpoint_inference: False
    breakpoint_inference_on_failure_code_extraction: False
    breakpoint_inference_on_failure_code_execution: False
    # Whether to breakpoint on update events
    breakpoint_update: False
    breakpoint_update_on_failure_code_extraction: True
    breakpoint_update_on_failure_pc_code_saving: True
    breakpoint_update_on_failure_sc_code_execution: True
    
  config_logs: ${config_logs}