name: LLM-HCG
config:
  model: gpt-4o-mini
  num_attempts_sc: 5

  config_logs:
    log_dir: logs
    do_log_on_new: True
    do_log_on_last: True

  config_debug:
    breakpoint_on_new_t: True
    breakpoint_on_failed_sc_extraction: True